name: sync-fork
on:
  schedule:
    - cron: '4 2 * * 4,2'
  workflow_dispatch:
jobs:
  sync-fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          gh auth login
          gh auth refresh --scopes workflow
          gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_HOST: github.com
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
