name: sync-fork
on:
  schedule:
    - cron: '4 2 * * 4,2'
  workflow_dispatch:
jobs:
  sync-fork:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
          unset GITHUB_TOKEN
          echo "${TOKEN}" | gh auth login --with-token
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_HOST: github.com
      - run: gh auth refresh --scopes workflow --hostname github.com
      - run: gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
